name: CI muraleetharan.ch

on:
    push:
        branches-ignore:
            - main
    pull_request:
        types: [opened, reopened]


jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: use Node.JS
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: Install node modules
              run: npm install
            - name: Run build
              run: npm run build
